In [ ]:
'''
The Variable() constructor requires an initial value for the varible , 
which can be a Tensor of any type and shape.
this initial value defines the type and shape of the variable after construction , the type and shape of the variable of are
fixed . The value can be changed using one of the assign methods.
'''

In [2]:
import tensorflow as tf

In [3]:
tf.Variable(1) # by default name "VAriable:0" 

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [4]:
a = tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>

In [5]:
a.shape

TensorShape([4])

In [6]:
a.dtype

tf.int32

In [7]:
a.numpy() # to convert value to numpy 

array([1, 2, 3, 4])

In [8]:
type(a) # 

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [9]:
t_f = tf.Variable(['a','c','d'])
t_f

<tf.Variable 'Variable:0' shape=(3,) dtype=string, numpy=array([b'a', b'c', b'd'], dtype=object)>

In [11]:
t_b = tf.Variable([True , False , True , True])
t_b

<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([ True, False,  True,  True])>

In [14]:
t_c = tf.Variable([5+6j, 7+11j])
t_c

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5. +6.j, 7.+11.j])>

In [16]:
CONSTANT = tf.constant([1,2,3,4,5,6])
CONSTANT

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [17]:
tf.Variable(CONSTANT)

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [18]:
tf.Variable([[1,2],[4,5]])

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [4, 5]])>

In [25]:
x = tf.Variable([[1,2],[3,4]] , shape = (2,2) , dtype="float")
x

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [27]:
tf.reshape(tf.constant([1,2,3,4]) , (2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [30]:
tf.argmax(tf.reshape(CONSTANT , (2,3)))

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 1], dtype=int64)>

In [31]:
tf.argmax(tf.reshape(CONSTANT , (2,3))).numpy()

array([1, 1, 1], dtype=int64)

In [45]:
a = tf.Variable([1,2,3,4,5,6])
a
# we can't change shape and data type after create variable or constant 

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [44]:
a.assign([10,20,30,40,50,60]) # assign value to variable and store at some memory place 

<tf.Variable 'UnreadVariable' shape=(6,) dtype=int32, numpy=array([10, 20, 30, 40, 50, 60])>

In [42]:
a.assign_add([11,22,33,44,55,66]) # add value to previous assigned memory location get value and add it new value to that

<tf.Variable 'UnreadVariable' shape=(6,) dtype=int32, numpy=array([ 21,  42,  63,  84, 105, 126])>